# Exercise 3: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [8]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)

A

array([[0.57265814, 0.25375851, 0.01895627, 0.67712646, 0.83500969,
        0.0015099 , 0.00215909, 0.66153218, 0.91995618, 0.72273217],
       [0.95878831, 0.24510708, 0.92473375, 0.90661579, 0.72502336,
        0.17138453, 0.40009447, 0.62074813, 0.92290699, 0.29124126],
       [0.96446086, 0.10014939, 0.62890542, 0.67805434, 0.26963877,
        0.69508623, 0.3871574 , 0.51905313, 0.53512112, 0.61857942],
       [0.58891096, 0.58402565, 0.32722037, 0.6531373 , 0.68538894,
        0.25086203, 0.92214237, 0.49215308, 0.63631964, 0.9368421 ],
       [0.65104327, 0.17873734, 0.38364399, 0.70703686, 0.50670378,
        0.95549926, 0.2401595 , 0.61167853, 0.30533876, 0.8132768 ],
       [0.16165817, 0.42972367, 0.66435641, 0.24426479, 0.89208913,
        0.79094459, 0.91023634, 0.37121783, 0.5753813 , 0.97546485],
       [0.13355253, 0.74606129, 0.36613396, 0.00142695, 0.46398539,
        0.09259874, 0.36518336, 0.67944035, 0.44690021, 0.616785  ],
       [0.70866961, 0.45911353, 0.2459918

In [22]:
#3.3: return only the odd rows of A
A[::2]

array([[0.57265814, 0.25375851, 0.01895627, 0.67712646, 0.83500969,
        0.0015099 , 0.00215909, 0.66153218, 0.91995618, 0.72273217],
       [0.96446086, 0.10014939, 0.62890542, 0.67805434, 0.26963877,
        0.69508623, 0.3871574 , 0.51905313, 0.53512112, 0.61857942],
       [0.65104327, 0.17873734, 0.38364399, 0.70703686, 0.50670378,
        0.95549926, 0.2401595 , 0.61167853, 0.30533876, 0.8132768 ],
       [0.13355253, 0.74606129, 0.36613396, 0.00142695, 0.46398539,
        0.09259874, 0.36518336, 0.67944035, 0.44690021, 0.616785  ],
       [0.56840858, 0.29913416, 0.24427139, 0.1908499 , 0.79864703,
        0.54059623, 0.01634657, 0.02542025, 0.78570744, 0.54998396]])

In [15]:
#3.4: perform a matrix multiplication of A with it's transposed
np.dot(A, np.transpose(A))

array([[3.35472441, 3.31937139, 2.55853233, 3.09662893, 2.60259559,
        2.60757332, 1.96843731, 2.31666899, 2.34012501, 2.63674269],
       [3.31937139, 4.69345134, 3.61131105, 3.67700103, 3.18937548,
        3.28820485, 2.16300361, 2.85523811, 2.59653718, 3.38739909],
       [2.55853233, 3.61131105, 3.4396464 , 3.16678996, 3.24421543,
        3.02909587, 1.73895283, 2.63359309, 2.2324839 , 2.61502408],
       [3.09662893, 3.67700103, 3.16678996, 4.12939035, 3.14081535,
        3.83499376, 2.50968917, 2.99673208, 2.43981847, 3.68411379],
       [2.60259559, 3.18937548, 3.24421543, 3.14081535, 3.45909389,
        3.23208362, 1.82672688, 2.83246864, 2.2800639 , 2.60997385],
       [2.60757332, 3.28820485, 3.02909587, 3.83499376, 3.23208362,
        4.38217509, 2.5163525 , 3.11382741, 2.58226719, 3.9175038 ],
       [1.96843731, 2.16300361, 1.73895283, 2.50968917, 1.82672688,
        2.5163525 , 2.10749842, 1.74856564, 1.52300802, 2.92538927],
       [2.31666899, 2.85523811, 2.6335930

In [17]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[ 0.77445253, -0.82780713,  2.60453394, -0.67595763, -2.15685758,
        -0.09182825,  0.3606895 ,  1.3783946 , -0.62804434, -0.16266708],
       [-2.14342725,  0.88044085, -2.55354543,  1.89213084,  2.29302172,
        -1.92742136,  0.85650527, -0.83980029,  1.79848573,  0.11564372],
       [-0.76001033,  1.12177555, -0.34465836, -0.53574647,  0.07466452,
         0.69763092,  0.98756796, -0.34504535,  0.02229841, -0.69192066],
       [-1.39194872,  1.44877109, -3.13740454,  1.9335603 ,  3.02140844,
        -1.16242379, -0.69856599, -1.29580693,  0.93136143, -0.0218104 ],
       [ 1.12031668,  0.07063371,  0.08732749, -1.19625243, -1.04411237,
         0.99923467, -0.08134649,  1.38589881, -0.93097978, -0.16573236],
       [-0.71161893, -0.15696478, -0.57836814,  0.15139545,  1.45388117,
        -0.46222514, -0.69944088, -0.38854612,  0.83471196,  0.63176696],
       [ 0.40145986, -0.58896907,  1.12451484,  0.31101638, -1.23387479,
         0.49308064, -0.89055807,  0.50912518

In [23]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask=A>0.5
A[mask]/=2
A

array([[0.28632907, 0.25375851, 0.01895627, 0.33856323, 0.41750484,
        0.0015099 , 0.00215909, 0.33076609, 0.45997809, 0.36136609],
       [0.47939416, 0.24510708, 0.46236687, 0.45330789, 0.36251168,
        0.17138453, 0.40009447, 0.31037406, 0.46145349, 0.29124126],
       [0.48223043, 0.10014939, 0.31445271, 0.33902717, 0.26963877,
        0.34754311, 0.3871574 , 0.25952657, 0.26756056, 0.30928971],
       [0.29445548, 0.29201282, 0.32722037, 0.32656865, 0.34269447,
        0.25086203, 0.46107118, 0.49215308, 0.31815982, 0.46842105],
       [0.32552164, 0.17873734, 0.38364399, 0.35351843, 0.25335189,
        0.47774963, 0.2401595 , 0.30583927, 0.30533876, 0.4066384 ],
       [0.16165817, 0.42972367, 0.33217821, 0.24426479, 0.44604457,
        0.3954723 , 0.45511817, 0.37121783, 0.28769065, 0.48773243],
       [0.13355253, 0.37303065, 0.36613396, 0.00142695, 0.46398539,
        0.09259874, 0.36518336, 0.33972017, 0.44690021, 0.3083925 ],
       [0.3543348 , 0.45911353, 0.2459918